### ISSUE TITLE
setStaticDirname is not working for "."

### ISSUE THREAD

**Issue by peteroid** [alberto-bottarini/httpdispatcher#13]
As line 79 is `var filename = "." + require('path').join(this.staticDirname, url.pathname);`, we should not use this method with ".". It will generate a path like this: ".public" instead of "./public". 

One solution for this is: `setStaticDirname("");`

**Comment by caffeinewriter** [comment]
In general, the implementation should be redone, since it breaks absolute paths completely, unless you basically go `./../../../../../../` until you're at the FS root. Not to mention the static directory prefix isn't stripped when checking for resources to serve up. (E.g., specify static directory as `resources`, the static directory would need to contain a `resources` folder. I feel like it also partially relates to #8.

**Comment by alberto-bottarini** [comment]
fixed in 1.1.0
