### ISSUE TITLE
Support PUT and DELETE methods

### ISSUE THREAD

**Issue by andrei128x** [alberto-bottarini/httpdispatcher#14]
Hello, is it possible to add support for PUT and DELETE methods ?
Gread module, btw.

**Comment by besworks** [comment]
I added onPut and onDelete methods for my own use. Not heavily tested but seems to work.

[httpdispatcher_put_and_delete_support.zip](https://github.com/alberto-bottarini/httpdispatcher/files/271580/httpdispatcher_put_and_delete_support.zip)

**Comment by alberto-bottarini** [comment]
@besworks why not create a PR?

**Comment by besworks** [comment]
@alberto-bottarini, I didn't think it was appropriate. I didn't even check out the repo. I hacked this functionality in after installing via npm and barely tested it. Just figured I should share it here so that anyone else looking for these features could build off the changes that I made. I had some time today so I went ahead and branched it properly. I'm about to submit a PR now.

**Comment by alberto-bottarini** [comment]
#17 adds missing methods.
Issue closed, thanks.
