### ISSUE TITLE
Load static resource error

### ISSUE THREAD

**Issue by LeonardoBorselli** [alberto-bottarini/httpdispatcher#29]
Hi,
i'm using httpdispatcher. I think it's very useful. 

dispatcher.setStaticDirname('static');
dispatcher.setStatic('/resources');
to access static resources in ./static directory (relative to the package root) and get an error in this line

            "Content-Type": require('mime').lookup(filename)
                                            ^

this is because mime package has renamed lookup() to getType()
I've changed httpdispatcher.js:131 accordingly

"Content-Type": require('mime').getType(filename)

now it works fine.

Thanks.

**Comment by alberto-bottarini** [comment]
Please upgrade to 2.1.1

**Comment by cassiodoroVicinetti** [comment]
This issue broke all applications having `"httpdispatcher": "=2.1.0"` inside their package.json files, forcing them to upgrade to version 2.1.1. In the future it would be appreciated if breaking changes coming from sub-level dependencies were avoided by changing the definition of this dependency in a more conservative way (e.g. `"mime-types": "^1.2.5"` instead of `"mime-types": ">=1.2.5"`).
